### ISSUE TITLE
Allow HTTPS protocol for license and other URIs

### ISSUE THREAD

**Issue by jesusbagpuss** [antleaf/rioxx#1]
The RIOXX specification specifies HTTP URIs, but for most (all?) applications either HTTP or HTTPS should be considered complaint.

The EPrints plugin was written around the RIOXX spec 'as written' - and flags HTTPS URIs as non-compliant, which is generally unexpected by EPrints users.

https://github.com/eprintsug/rioxx2/issues/39
https://github.com/eprintsug/rioxx2/blob/master/lib/plugins/EPrints/RIOXX2/Utils.pm#L48-L58

**Comment by paulwalk** [comment]
I think there is a reasonable convention of using the phrase "HTTP URI" to also include HTTPS URIs, since the 'identifier' part of the protocol is essentially the same.

However, there is no harm in making a comment to this effect in the RIOXX spec, to make this unambiguous.

I propose that RIOXX should accept HTTP and HTTPS URIs interchangeably.

**Comment by petrknoth** [comment]
+1

**Comment by paulwalk** [comment]
The new draft profile has been amended to allow either HTTP or HTTPS where appropriate.
