### ISSUE TITLE
Include field for DOI

### ISSUE THREAD

**Issue by jesusbagpuss** [antleaf/rioxx#10]
The DOI can sometimes be present in the RIOXX representation as part of a link in the  `version_of_record` element.

Having an explicit DOI field might be appropriate - especially for e.g. CORE using the RIOXX profile for mass-harvests.

In a standard DC representation of an item, multiple `dc:identifier`s can be output. 
The RIOXX profile declares only one `dc:identifier` field is allowed (https://github.com/antleaf/rioxx/blob/master/webroot/static/schema/v2.0/rioxx/rioxx.xsd#L138-L156), and also that:  

> it is RECOMMENDED that this identifier should point to the _actual resource
being described by the RIOXX record_  

- so the DOI (pointing to a publisher's version) should *NOT* be used here.

Having a standard field, with explicit rules for the content e.g. "just the 10.xxxx/yyyy; not a link; no doi resolver" might make this more useful for downstream systems.

**Comment by geo-mac** [comment]
Just checking my brain is working correctly John: are you suggesting that the carnality of `dc:identifier` be changed to allow for one or more, perhaps controlled through element refinements or content rules...? In which case, is `rioxxterms:version_of_record` then deprecated?

My understanding is that CORE-esque mass-harvests are usefully employing `rioxxterms:version_of_record`.

**Comment by paulwalk** [comment]
We have a separate property for the identifier that the publisher considers to be the version of record. We require a URI for this property. That can be a DOI.

> The DOI can sometimes be present in the RIOXX representation as part of a link in the version_of_record element.

The DOI represented as a URL is the approach recommended by the main Registration Agency (CrossRef) in this domain.

**Comment by jesusbagpuss** [comment]
Just checking - with the Plan S requirements in mind - which will result in a DOI being created for an Author Accepted Manuscript, distinct to the publisher's DOI for the item.
Both these will need to be represented in these records (IMO _any_ PIDs related to this record should be represented).

**Comment by geo-mac** [comment]
The RIOXX governance group is meeting in the next week or so to discuss an expansion to the use of dc:identifier -- although the topic for discussion is more about capturing different 'expressions' of the same work rather than the question you raise.

I think there are two issues in this particular space at the moment. The first is the assumption that RIOXX should expose Plan S compliant data (whatever that might mean!). Is this assumption correct? Perhaps not. The principal motivation behind revising RIOXX is to improve large-scale content aggregation and ergo discovery. Exposing Plan S data was never an objective. Of course, Plan S and aggregation need not be mutually exclusive, and it doesn't mean Plan S shouldn't be considered; but it wasn't necessarily a starting point in this instance. 

The second issue is that PID use for the purposes of Plan S compliance appears undecided at the moment, with DOIs not necessarily considered the best option. In fact, there doesn't appear to be a preferred PID option at the moment! [Check out this recent summary from Open Repositories 2021](http://doi.org/10.5281/zenodo.4945533). Further community thinking is necessary, I think. 

On the matter of PIDs, I also have concerns about repositories in a 'slave' relationship with a CRIS. The manner in which CRIS implementations interact with connected repositories leaves little control over the minting of PIDs, control over versioning, etc. Some further thinking is needed from the repository and scholarly communications community on this too.

**Comment by jesusbagpuss** [comment]
Yes - the Plan S / AAM DOIs stuff is horrible and messy.
It's made slightly more palatable by the ability to link DOIs together in DataCite (_the DOI I'm minting is a version of this publisher's DOI_ sort of thing).

>the assumption that RIOXX should expose Plan S compliant data

This wasn't my assumption. My story-line was more:
- my repo should be Plan S compliant
- I will be creating PIDs for material in my repo that _will_ be different to a PID for a published version of the same work
- RIOXX is describing a specific document in my repo, but not using the DOI I have created for it, if using the VoR DOI

Any yes, the CRIS angle is _fun_...

**Comment by geo-mac** [comment]
> Yes - the Plan S / AAM DOIs stuff is horrible and messy.

Absolutely! I'm feeling slightly queasy thinking about it!

I agree with your story-line btw, and it is something we'll need to consider, if not now then the near future.

**Comment by paulwalk** [comment]
Regarding:

> RIOXX is describing a specific document in my repo, but not using the DOI I have created for it, if using the VoR DOI

I have recently made a proposal (to be discusses by the Governance Group) that the semantics of the ID property in RIOXX be changed so that it can be used to identify the "work" being described by the RIOXX "record". This would allow for the use of a new DOI for an AAM for example, but also would allow for use of the URL for the repository record "splash page" (or indeed any other URL)

**Comment by paulwalk** [comment]
Regarding serving PlanS: while this is not our focus, it would be naive to ignore it. We should probably run our proposed version 3.0 profile through a quick process of evaluation in terms of helping/hindering PlanS...

**Comment by geo-mac** [comment]
>  the semantics of the ID property in RIOXX be changed so that it can be used to identify the "work" being described by the RIOXX "record". 

"expressions", "works", etc. It's all getting a bit too FRBR now, isn't it?! Please..... no! ;-)

**Comment by paulwalk** [comment]
I know.... I flinch every time I say "works"! But that is probably the best term to be honest - it's the one used in Samvera/Hyrax too.
