### ISSUE TITLE
How should multiple URIs for the same 'thing' be represented?

### ISSUE THREAD

**Issue by jesusbagpuss** [antleaf/rioxx#44]
The [`rioxxterms:author` documentation](https://github.com/antleaf/rioxx/blob/master/webroot/content/profiles/v3-0-rc-1/rioxxterms_author.md?plain=1#L27) lists multiple PID systems that might be listed in a URI, but doesn't explain how we should present multiple URIs - e.g. an ORCID and an ISNI for the same author.

Other 'things' may also have multiple PIDs (e.g. a ROR and a DOI).

A similar train of thought exists here: https://github.com/dcmi/pids_in_dc/issues/17

We should **NOT** rely on the PID systems joining these records together in some way. If we _know_ a 'thing' has multiple PIDs we must be able to represent them all.

**Comment by geo-mac** [comment]
Not sure I follow. Just to check, are you asking how we might encode an author who has, for example, both an ORCID and an ISNI, and how both might be encoded simultaneously?

**Comment by jesusbagpuss** [comment]
Yes - representing multiple PIDs via URIs at the same time.
From the linked 'pids in dc' issue, we could use whitespace to delineate (which works well with URIs that can't contain (un-encoded) whitespace.

We would have to make sure that URI attributes are always treated as possibly containing multiple URIs.

**Comment by jesusbagpuss** [comment]
```xml
<rioxxterms:author uri="https://isni.org/isni/0000000419368139 https://ror.org/00n3w3b69">
    University of Strathclyde
</rioxxterms:author>
```
sort of thing

**Comment by geo-mac** [comment]
I'm unsure whether multiple simultaneous PIDs was a use case the RGG ever discussed TBH! But I agree with your proposal, and it makes sense to accommodate it explicitly in the spec. The RGG is due a meeting so this and few other proposals can be discussed and actioned then. Cheers John!

**Comment by paulwalk** [comment]
I'm curious - what is the use case for RIOXX recording multiple PIDs for the same entity?

To test this, I'll argue against it:

* we include PIDs in our metadata spec in order to unambiguously identify an entity (author, paper...)
* one PID is sufficient for this
* RIOXX is not intended (at least so far) to be a PID-relating/mapping service
* adding support for multiple PIDs for one entity introduces the possibility of internal inconsistency. This is avodable by only using one PID

**Comment by geo-mac** [comment]
> I'm curious - what is the use case for RIOXX recording multiple PIDs for the same entity?

@jesusbagpuss may have a clearer explanation. But I suppose the use case might be locally motivated, e.g. an organization would prefer to serve the richest data possible, enabling a more valuable contribution to the PID graph and greater disambiguation for users/machines. There are benefits to be gleaned from doing it and I can envisage many organizations adopting this view. But I take your point that the mechanics of the schema may not best accommodate it. And Rioxx is not necessarily in the business of accommodating it, even if it could.

**Comment by geo-mac** [comment]
Having said all that, we should definitely chew the cud! :-)

**Comment by paulwalk** [comment]
Yes - happy to discuss and certainly not set against the idea.

But one thing which I think has been successful in RIOXX is the avoidance of opportunities for internal contradiction. For example I fought against the inclusion of both "licenseref" and "freetoread" - which could contradict each other in the same record (I was overruled by JISC at the time - but I'm happy that we have rectified this in v3.x)

**Comment by jesusbagpuss** [comment]
@geo-mac - yes - as a repository developer, I don't want to make a decision as to which PID system is correct for any given application. Share all PIDs equally!
> If an entity has a PID, whenever and wherever that entity is presented, it should include the PID.

@paulwalk - I think your first statement should be 'we include PIDs in our metadata profile to allow downstream systems to accurately identify an entity'. Multiple PIDs for an entity does not break this.

The metadata profile is about sharing information.
If a repository system knows multiple PIDs for an entity, it should be able to present them all. The profile should NOT judge which PID may be most appropriate for a downstream system to be passed.

In not supporting multiple PIDs for an entity, you're asking systems to make a preference for e.g. ORCIDs over ISNIs. This is not something that I am happy doing. I don't know which PID system is most useful to a downstream system.

If a repository has contradictory information for an entity, this should be corrected, not hidden because a metadata profile is scared of exposing it as such 😉

**Comment by paulwalk** [comment]
> @paulwalk - I think your first statement should be 'we include PIDs in our metadata profile to allow downstream systems to accurately identify an entity'.

Well, I was and still am quite happy with my original sentence ;-)

> Multiple PIDs for an entity does not break this.

Now that you have re-written my statement, perhaps you are right. But I intentionally used the word "unambiguously" in my original statement. Associating multiple PIDs to the same entity does introduce the possibility of ambiguity.

> In not supporting multiple PIDs for an entity, you're asking systems to make a preference for e.g. ORCIDs over ISNIs. This is not something that I am happy doing. I don't know which PID system is most useful to a downstream system.

I don't really follow this logic at all. You have already made a preference in your system. It is perfectly reasonable to expect a system to make such a preference. After all, it is just not reasonable to expect every system to support every new flavour of PID. From another point of view, it is just as (perhaps more) reasonable to expect the downstream system to be prepared to deal with a range of PIDs:

""be conservative in what you do, be liberal in what you accept from others" ([Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle))

Look, I'm firmly of the view that RIOXX should, above all, be useful. Its development has always been driven by pragmatism. You clearly believe that associating more PIDs with properties in a RIOXX record will be useful, so we will definitely consider this.

On a relate note - it was actually me who initiated the DCMI work that you linked at the top of this thread, so it's not as though I am implacably opposed to the idea!

**Comment by ajtag** [comment]
From reading the docs, the URI attribute is not just limited to <rioxxterms:author>
but also includes <rioxxterms:contributor>, <rioxxterms:project> and <dc:publisher>

It is certainly the case that at date of initial publication we may not have all the metadata, and as records are augumented over time with existing PIDs or new PID systems are incorperated into workflows. only allowing one PID per entity, will force a decision on out part as to what to pick.

When I initially considered this issue, I was worried about being able to identify the type of PID, but I think a requirement as suggetsed of url-encoded. and space delimited should cover that.

**Comment by geo-mac** [comment]
The [recent RGG meeting](https://www.rioxx.net/governance/minutes/2022-11-07/) considered this proposal and the issues surrounding it. The Group agreed with @jesusbagpuss that it should be possible to include multiple URIs, however there was disagreement as to the approach. ]

The 'white space' approach -- while not unprecedented as per the DCMI example -- was considered a non-standard XML workaround and therefore an undesirable solution. The alternative albeit imperfect compromise was simply to propose that the property be repeated as necessary, with each repetition referencing the additional PID, e.g. one for ORCID, one for VIAF, and so on. This has the drawback of requiring de-duplication downstream but will likely be simpler for aggregators to parse.

From the minutes you'll note that there is a general concern about the proliferation of PIDs defining the same thing.

**Comment by jesusbagpuss** [comment]
Having skim-read the meeting notes:
`<rioxxterms:author uri="https://isni.org/isni/0000000056397298"> Brian Cox </rioxxterms:author> <rioxxterms:author uri="https://orcid.org/equivalent-orcid-for-prof-brian-cox"> Brian Cox </rioxxterms:author>`

_Two authors, both called 'Brian Cox'..?_ not unheard of I suppose... 😉 

This (almost) feels worse than not being able to support multiple PIDs.

> drawback of requiring de-duplication downstream but will likely be simpler for aggregators to parse.

I'm not sure I agree. The whitespace solution requires the ability to find space characters in an attribute value (spaces in attribute _values_ are not normally non-standard*).
The deduplication approach needs some other data-source to validate that the two PIDs either both relate to the same entity, or don't (in which case there _were_ two authors called Brian).
This is harder to solve. Two downstream systems with different integrations to determine 'sameness' of two author elements may represent the above as two authors, or one author with two PIDs. We've introduced _more_ chaos.

Not sure if there are any other metadata schema that would represent one author with two author elements? It feels messy.

The following suggestion feels as messy as the above, but leaves one URI for systems that can't handle splitting-on-whitespace, and a fuller list for those that can:
`<rioxxterms:author uri="https://isni.org/isni/0000000056397298" additional-pids="https://doi.org/10.1234/doi-for-brian https://orcid.org/equivalent-orcid-for-prof-brian-cox">Brian Cox</rioxxterms:author>`

## *whitespace in XML attribute values
If an attribute is defined as a 'string type', space is OK in the value (space is never OK in the attribute name).
Other attribute types do not allow whitespace. https://www.w3.org/TR/2008/REC-xml-20081126/#sec-attribute-types.

From what I can see, the previous versions of RIOXX don't refine the `<dc:creator>` element to create `<rioxx:author>`, and (I think - may have overlooked some XSD inheritance) that we could therefore define the URI attribute as a'string type'?

**Comment by jesusbagpuss** [comment]
NB the above isn't a hard-sell _for_ the whitespace option. It _is_ a _eughh_ for the repeated-author-elements-for-one-author.

**Comment by geo-mac** [comment]
Cheers @jesusbagpuss for this detailed response! Yes, I would be inclined to agree with:

> This (almost) feels worse than not being able to support multiple PIDs.

So, on reflection, it may be preferable to temporarily park this question until there is consensus about how best to solve it. It won't take long for thinking to mature, and I have it as an agenda item to be revisited.  

Your quip about 'Brian Cox' is amusing but highlights that this is a bad example to use! 'Brian Cox' is often used in such examples because he is a celebrity scholar but here he is completely inappropriate! :-)

**Comment by ajtag** [comment]
When considering this issue, my gut reaction was the solution would require specifying the type otherwise, the strings in the list of pids are going to be ambiguous. 

It is OK if they are in the style of a fully qualified URI as in the examples, but i worry repository staff are unlikely to qualify all PIDs coming past their desks.

Perhaps I am going off piste here, but my first thoughts on the solution was to have attributes specified something like 
orcid="..." viaf="..." space_seperated_list_because_we_dont_know_the_type="..."
or an explicit list of tags <pid type="..">...</pid> within the creator element.

This may also be going down a rabbit hole of needing a controled vocab for PID types, and thats not good either.

But that felt better than trying to guess what kind of a pids you had from the pid-string (how many pids are n-digit strings?).
Having an optional type hint allows the encoder to encode as much as they are able and the decoder to choose which type hints to follow.

I am not going to claim to be proposing this is best-practice XML design here, only that a space seperated list may will require the parser to work it out when it may be easier to encode the type with the pid.

edited to change pid:orcid  to orcid as not certain pid:orcid would be valid xml,

**Comment by ajtag** [comment]
from the docs, the following fields are also documented as able to take PIDs in this form: <rioxxterms:author>, <rioxxterms:contributor>, <rioxxterms:project> and <dc:publisher>

**Comment by geo-mac** [comment]
> When considering this issue, my gut reaction was the solution would require specifying the type otherwise, the strings in the list of pids are going to be ambiguous.

I think, as you suggest yourself, that this could be a bit of a rabbit hole, and might actually support the argument of @jesusbagpuss insofar as one would not wish to make assumptions about the types of URIs/PIDs to be accommodated. The URIs shouldn't be ambiguous though. They should be unique, irrespective of which agency has created them.

**Comment by ajtag** [comment]
when I mentioned ambiguity, my thoughts were more on the type of identifier, rather than duplication of identifiers.
so after splitting the string, de-coding, is the resulting string a VIAF identifier or ORCID? and so what can I do with it/ how do I need to handle it.

So long as it is the fully qualified version is the content popoulating the field, it should be simple to identify the type.
I have been through the spec again, and I cant find any places where the URI attribute is used and doesnt have a fully qualified version.
The closest was local grant codes and funderid, but they are not relevent here. 

on the encoding side 
I do think implementations need to be carefull to ensure it is fully qualified, especially when the data is coming from users.

on the de-coding/ processing side 
When I think about the operations of processing a set of records in RIOXX form having multiple unknown things in the field adds complexity.

There is no doubt the @jesusbagpuss solution would work, it just feels like a compromise, and glad to finding the best answer.

**Comment by jesusbagpuss** [comment]
> I do think implementations need to be carefull to ensure it is fully qualified, especially when the data is coming from users

 In addition, I think that any XSLT that may be used to display RIOXXv3 records to a human e.g. via OAI-PMH should flag correctness of this value. (I'd even be tempted to display known schema with logos/icons for them. Sounds like some 'fun' XSLT to craft!)

**Comment by petrknoth** [comment]
I feel that multiple PIDs for an entity should be supported. It seems to me that a clean option of dealing with the modelling issue of multiple URLs for an entity might be to model what is in the attribute as an element. 

This would require changing this:
```xml
<rioxxterms:author uri="https://isni.org/isni/0000000419368139 https://ror.org/00n3w3b69">
    Brian Cox
</rioxxterms:author>
```

into something like this:
```xml
<rioxxterms:author>
    <name>Brian Cox</name>
    <uri>https://isni.org/isni/0000000419368139</uri>
    <uri>https://ror.org/00n3w3b69</uri>
</rioxxterms:author>
```

**Comment by paulwalk** [comment]
@petrknoth - I agree with you, I think this approach is better.

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
