### ISSUE TITLE
Require rioxxterms:publication_date to be encoded as ISO 8601 (post–2004 versions)

### ISSUE THREAD

**Issue by petrknoth** [antleaf/rioxx#6]
The current RIOXX specification defines the domain of the publication_date field as free text. For example, this is permissible under the current spec: 

<rioxxterms:publication_date>
    Spring, 2010
</rioxxterms:publication_date>

I propose that this field is required to be encoded as ISO 8601 (post–2004 versions). For example, 

<rioxxterms:publication_date>
    2011-02-23
</rioxxterms:publication_date>

Rationale: Checking this field is useful in the context of verifying funder policy compliance. A proper encoding of the date will make this procedure easier.

**Comment by geo-mac** [comment]
This certainly appeals to be my technical pedantry! *However*, the rationale for doing it is not a new one and must surely have been considered previously. After all, encoding dates according to the ISO date and time format has been par for the course since forever! 

I therefore wonder whether the relaxation of publication_date to free-text was originally in order to accommodate publications which do not provide a verifiable date of publication, e.g. journal titles published by learned societies? Such publishers are notoriously vague in providing publication dates, making ISO DTF dates problematic.

@antleaf Were there discussions about this previously in V2 of RIOXX?  

We could, of course, control for the vagueness of publishers by the tightening the scope of publication_date via the inclusion of detailed scope notes on re-specifying 'vague dates' as ISO DTF (?). For example: 

- Publication dates indicating month of publication only (e.g. October 2019) and lacking a day of publication, should specify the day as the last day of the publication month (e.g. 2019-10-31).

- Publications lacking a specific publication date and instead relying on assignation to seasonal issues (e.g. Autumn 2019, Spring 2020, etc.) should use the following key to re-specify an ISO DTF compliant date...... / some conventions on specifying dates /

**Comment by paulwalk** [comment]
Yes - this was argued about at the beginning of the development of RIOXX. The problem was simply that proper dates were not reliably provided by publishers. It is surprisingly difficult in some cases to determine this date.

Adopting  convention is as @geo-mac suggests is certainly possible. 

I will be publicising these issues for public comment , but following that, this is the sort of thing that the Governance Group can decide :-)

**Comment by jesusbagpuss** [comment]
Would allowing either W3CDTF _or_ ISO8601 dates be an option?
I think it gives us flexibility alongside better support for null parts (eg. only a year is known).

It's the route that [MODS has taken](https://www.loc.gov/standards/mods/v3/mods-userguide-generalapp.html):

> Date Attributes. Certain date attributes may be applied to some MODS elements, as indicated in the schema. They are defined below:
    encoding - The following values are used with the encoding attribute:
        w3cdtf - This value is used for the profile of ISO 8601 that specifies the following date pattern: YYYY-MM-DD.
        iso8601 - This value is used for formatted dates allowed in ISO 8601 which use the alternative described as "basic" rather than "extended". This alternative specified in the standard uses the following date pattern: YYYYMMDD (hours, minutes, seconds may also be added). It is also used for other encodings specified in ISO 8601, e.g. date ranges, which are in the form of YYYY/YYYY (in which case start and end portions are not parsed). The ISO 8601 basic expression has been used widely in MARC 21 date elements.
        marc - This value is used only for dates coded according to MARC 21 rules in field 008/07-14 for dates of publication/issuance. Thus, this would only apply to the attribute in <dateIssued>. Examples include: 19uu (a MARC convention to show unknown digits in a date), 9999 (a MARC convention showing that the end date has not occurred or is not known).

NB I'm not suggesting we should also support marc...

**Comment by paulwalk** [comment]
superseded by launch of Rioxx version 3.0 - closing this issue
